name = "certified-payroll"
type = "pages"
compatibility_date = "2023-10-12"

[build]
  command = "npm run build"
  directory = "."
  output_directory = "dist"

[dev]
  command = "npm run dev"
  directory = "."
  open = true
  port = 3000

[pages]
  pages_build_output_dir = "./dist"
